// PRODUCTION Firebase configuration.
// Generated by FlutterFire CLI — do not edit manually.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class ProdFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'ProdFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'ProdFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy4OTMjMItIsvIt1D9Edn8_f0k3y4Ifbs',
    appId: '1:737814594801:android:9cd1721d8a97c810fed550',
    messagingSenderId: '737814594801',
    projectId: 'event-management-b8187',
    storageBucket: 'event-management-b8187.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdOaKN1shhyoW1wpZqknsjIMTR0Ycne-c',
    appId: '1:737814594801:ios:59040b399ecbbcc1fed550',
    messagingSenderId: '737814594801',
    projectId: 'event-management-b8187',
    storageBucket: 'event-management-b8187.firebasestorage.app',
    iosBundleId: 'com.example.eventmanage.eventManagement',
  );
}
